config/routes.rb
TUMWeb::Application.routes.draw do

  match 'locales/es' => 'locales#spanish'
  match 'locales/en' => 'locales#english'
  resources :web, :only => [:index, :presentation] do
    collection do
      get :presentation
    end
  end

  root :to => 'welcome#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  protected
  def set_access_control_headers
    
    headers['Access-Control-Allow-Origin'] = request.env['HTTP_ORIGIN']
    headers['Access-Control-Allow-Methods'] = 'GET'
    headers['Access-Control-Max-Age'] = '1000'
    headers['Access-Control-Allow-Headers'] = '*,x-requested-with'
  end

end

app/controllers/locales_controller.rb
class LocalesController < ApplicationController
    
  def spanish
    I18n.locale = :es_MX
    finish_request
  end
  
  def english
    I18n.locale = :en
    finish_request
  end
  
  private
  def finish_request
    redirect_to :back
  end
end

app/controllers/web_controller.rb
class WebController < ApplicationController
	def index
	end
	
	def presentation
	  send_file(Rails.root+"public/PresentacionPumabusMovil.pdf")
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  layout 'landing_page'

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locales_helper.rb
module LocalesHelper
end

app/helpers/web_helper.rb
module WebHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pumabus Móvil : Web</title>

  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>

  <!--<script src='http://maps.google.com/maps/api/js?sensor=false' type='text/javascript'></script>-->
  <link rel='stylesheet' type='text/css' href='http://fonts.googleapis.com/css?family=Magra:400,700'>
	<!--[if lt IE 8]>
		<link rel="stylesheet" href="../assets/leaflet.ie.css" />
		#sequence li, #sequence li * {
		    /*By making sure IE filters never run, jQuery won't animate a fade between frames in IE6/7/8. This prevents the black halo around transparent images.*/
		    filter: "" !important;
		    -ms-filter: "" !important;
		}
	<![endif]-->
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/landing_page.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pumabus Móvil</title>
  <%= stylesheet_link_tag    "landing_page", :media => "all" %>
	<link rel='stylesheet' type='text/css' href='http://fonts.googleapis.com/css?family=Magra:400,700'>
	<%= javascript_include_tag "landing_page" %>
	<!--[if lt IE 8]>
		#sequence li, #sequence li * {
		    /*By making sure IE filters never run, jQuery won't animate a fade between frames in IE6/7/8. This prevents the black halo around transparent images.*/
		    filter: "" !important;
		    -ms-filter: "" !important;
		}
	<![endif]-->
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>

</html>

app/views/web/index.html.erb
<div id="map" style="padding: 0pt; overflow: hidden; cursor: default;"></div>

<div id="right-panel-extended">
	<h1><span class="emph">Pumabús Movil </span>Web</h1>
	
	<div class="content">
		<div class="vehicle-details">
			<div class="loader"></div>
		</div>
	</div>
</div>

<div id="right-panel">
	<h1><span class="emph">Pumabús Movil </span>Web</h1>
	
	<div class="content">
		<div class="menuPlaceHolder"></div>
		
		<ul class="routes"></ul>
		<div class="timetables"></div>
		<div class="about"></div>
	</div>
	<div class="langPlaceHolder"></div>
</div>

<div id="pumabus-movil"><a class="image" href="<%= root_path %>"></a></div>

<script id="content-for-lang-placeholder" type="text/x-handlebars-template">
	<div class="lang-choose">
		<a href="javascript:void(0);" class="home-lang">{{ linkLang }}</a>
	</div>
</script>

<script id="content-for-menu-placeholder" type="text/x-handlebars-template">
	<ul class="menu">
		<li class="routes-entry"><a href="#/routes">{{ linkRoutes }}</a></li>
		<li class="timetables-entry"><a href="#/timetables">{{ linkTimetables }}</a></li>
		<li class="about-entry"><a href="#/about">{{ linkAbout }}</a></li>
	</ul>
</script>

<script id="route-details-template" type="text/x-handlebars-template">
  <li id="{{ id }}" route="{{ lineNumber }}">
		<div class="details">
			<h1>{{ lineNumber }}</h1>
			<div class="endpoints">
				<h2>{{ leftTerminal }}</h2>
				<h2>{{ rightTerminal }}</h2>
			</div>
			<div class="color"></div>
		</div>
	</li>
</script>

<script id="timetables-template" type="text/x-handlebars-template">
	<h1>{{ weekdays }}</h1>
	<p>{{ weekdaysDetails }}</p>
	
	<h1>{{ saturdays }}</h1>
	<p>{{ saturdaysDetailsOne }}</p>
	<p>{{ saturdaysDetailsTwo }}</p>
	
	<h1>{{ sundays }}</h1>
	<p>{{ sundaysDetails }}</p>
</script>

<script id="about-template" type="text/x-handlebars-template">
	<p class="intro">{{ projectCredits }}</p>
	<div id="pictures">
		<div class="slides_container">
			<div>
				<%= image_tag "unam_small.png" %>
			</div>
			<div>
				<%= image_tag "IIMAS_small.jpg", :class => "iimas" %>
			</div>
			<div>
				<%= image_tag "pumabus_small.png", :class => "pumabus" %>
			</div>
		</div>
	</div>
	<p class="main">{{ projectConsiderationsMain }}</p>
	<p class="disclaimer">{{ projectConsiderationsDisclaimer }}</p>
	
	<p class="version">{{ app_version }}</p>
</script>

<script id="vehicle-template" type="text/x-handlebars-template">
	<div class="identificators">
		<p class="bus">PUMABUS</p>
		<p class="number"># {{ busNumber }}</p>
	</div>
	<div class="line">
		<p class="origin">{{ lineOrigin }}</p>
		<p class="destination">{{ lineDestination }}</p>
	</div>

	<p class="speed">{{ speedPrelude }} {{ busSpeed }} {{ speedMetrics }}</p>
	<p class="date">{{ reportTimestampPrelude }} {{ busReportTimestamp }}</p>
	
	<div class="way-out">
		<%= link_to image_tag('return.png'), "#{web_index_path}#/clearVehicleSelection" %>
	</div>
</script>

app/views/welcome/_sequence.html.erb
<ul class="controls">
	<li class="prev"></li>
	<li class="next"></li>
</ul>
<div id="sequence">
	<ul>
		<li>
			<div class="intro animate-in">
				<h2><%= t('home.one.title') %></h2>
				<h3><%= t('home.one.idea') %></h3>
			</div>
			<!--<a href="#" class="ios-logo"></a>-->
			
			<img class="iphone animate-in" src="../assets/iphone.png" alt="Versión iOS" />
			<img class="iphone-shadow animate-in" src="../assets/iphone-shadow.png" alt="" />
		</li>
		<li>
			<img class="galaxy" src="../assets/galaxy.png" alt="Versión Android" />
			<div class="slide2">
				<h2><%= t('home.two.title') %></h2>
				<h3><%= t('home.two.idea') %></h3>		
			</div>
			<!--<a href="#" class="android-logo"></a>-->
			
			<img class="galaxy-shadow" src="../assets/galaxy-shadow.png" alt="" />
		</li>
		<li>
			<div class="slide3">
				<h2><%= t('home.three.title') %></h2>
				<h3><%= t('home.three.idea') %></h3>
			</div>
			<%= link_to '', '#', :target => "blank", :class => "safari-logo" %>
			<%= link_to '', '#', :target => "blank", :class => "firefox-logo" %>
			<%= link_to '', '#', :target => "blank", :class => "chrome-logo" %>
			<img class="web" src="../assets/web.png" alt="Versión Web" />
			<img class="web-shadow" src="../assets/web-shadow.png" alt="" />
		</li>
	</ul>
</div>

app/views/welcome/index.html.erb
<div class="<%= I18n.locale == :en ? "soon" : "prox" %>"></div>

<div id="menu">
	<div id="decoration"></div>
	<div class="icono-navbar"></div>
	<ul>
		<li><%= link_to t('menu.home'), '#', :class => "home-trigger menu-link active" %></li>
		<li><%= link_to t('menu.details'), '#', :class => "details-trigger menu-link" %></li>
		<li><%= link_to t('menu.about'), '#', :class => "about-trigger menu-link" %></li>
		<li><%= link_to t('menu.team'), '#', :class => "team-trigger menu-link" %></li>
		<li><%= link_to t('menu.contribute'), '#', :class => "contribute-trigger menu-link" %></li>
		<% if PumaBusApp.locales_enabled? %>
			<li class="language">
				<% if I18n.locale.eql?(:es_MX) %>
					<%= link_to t('menu.lang.en'), locales_en_path, :class => "home-lang" %>
				<% elsif I18n.locale.eql?(:en) %>
					<%= link_to t('menu.lang.es'), locales_es_path, :class => "home-lang" %>
				<% end %>
			</li>
		<% end %>
	</ul>
	<%= link_to image_tag('unam_mini.png'), 'http://www.unam.mx', :target => "_blank", :class => "unam-logo" %>
</div>

<div id="scrollable-area">
	<div id="home" class="blocky">
		<%= render 'sequence' %>
	</div>
	
	<div id="communication">
		<div class="centered invite">
			<p>
				<strong><%= link_to t('communication.presentation.download'), presentation_web_index_path %></strong>
				<%= t('communication.presentation.notes') %>
			</p>
		</div>
	</div>
	
	<div id="details" class="blocky">

		
		<div class="centered container">
			
			<div class="os-selector">
				<ul>
					<li><a href="javascript:void(0);" id="ios" class="active selector"></a></li>
					<li><a href="javascript:void(0);" id="android" class="selector"></a></li>
				</ul>
			</div>
			
			<ul class="grid">
				<li class="active routes">
					<p class="title"><%= t('details.routes.title') %></p>
					<p class="description"><%= t('details.routes.description') %></p>
				</li>
				
				<li class="map">
					<p class="title"><%= t('details.map.title') %></p>
					<p class="description"><%= t('details.map.description') %></p>
				</li>
			
				<li class="real-time">
					<p class="title"><%= t('details.rt.title') %></p>
					<p class="description"><%= t('details.rt.description') %></p>
				</li>
				
				<li class="schedules">
					<p class="title"><%= t('details.schedules.title') %></p>
					<p class="description"><%= t('details.schedules.description') %></p>
				</li>
				
				<li class="places no-border">
					<p class="title"><%= t('details.places.title') %></p>
					<p class="description"><%= t('details.places.description') %></p>
				</li>
			</ul>
			

			
			<div id="screen-container" class="img-container">
				
				<div id="places_ios"></div>
				<div id="places_android"></div>
				
				<div id="schedules_android"></div>
				<div id="schedules_ios"></div>
				
				<div id="real-time_android"></div>
				<div id="real-time_ios"></div>
				
				<div id="map_ios"></div>
				<div id="map_android"></div>
				
				<div id="routes_ios"></div>
				<div id="routes_android"></div>
			</div>
		</div>
		
		<div class="centered bottom-final">
			<p><%= t('details.extra.one') %></p>
		</div>
	</div>
	
	<div id="about" class="blocky">
		<div class="labs">
			<div class="centered">
				<%= link_to "" ,"http://www.unam.mx", :target => "blank", :class => "unam-logo" %>
				<%= link_to "" ,"http://www.pumabus.unam.mx/", :target => "blank", :class => "pumabus-logo" %>
				<%= link_to "" ,"http://www.iimas.unam.mx/", :target => "blank", :class => "iimas-logo" %>
			</div>
		</div>
		<div class="two-contents centered">
			<h1><%= t('about.title') %></h1>
			
			<p><%= t('about.future.content_one') %></p>
			<p><%= t('about.future.content_two') %></p>
			<p><%= t('about.future.content_three') %></p>

			<div class="mid left">
				<h4><%= t('about.history.subtitle') %></h4>
				
				<p><%= t('about.history.content_one') %></p>
				<p><%= t('about.history.content_two') %></p>
				
			</div>
			
			<div class="mid right">
				<h4><%= t('about.future.subtitle') %></h4>

				<ol>
					<li class="odd"><%= t('about.future.ideas.one').html_safe %></li>
					<li><%= t('about.future.ideas.two').html_safe %></li>
					<li class="odd"><%= t('about.future.ideas.three').html_safe %></li>
					<li><%= t('about.future.ideas.four').html_safe %></li>
					<li class="odd"><%= t('about.future.ideas.five').html_safe %></li>
				</ol>
				
			</div>			
		</div>
	</div>

	<div id="team" class="blocky">
		<h1><%= t('team.title') %></h1>
		
		<ul class="members centered">
			<li>
				<p class="name">Dr. Juan Mario Peña Cabrera</p>
				<div class="photo centered pena"></div>
				
				<p class="description">Diseño, desarrollo y construcción de componentes de <i>hardware</i> y <i>software</i> especializados para el sistema de monitoreo y control vehicular para el transporte interno de la UNAM usando tecnología GPS y GPRS.</p>
				<p class="bio">Jefe del Departamento de Ingeniería de Sistemas Computacionales y Automatización en el IIMAS. </p>
				<p class="email">mario@leibniz.iimas.unam.mx</p>
			</li>
			<li>
				<p class="name">M. en I. Humberto Gómez Naranjo</p>
				<div class="photo centered naranjo"></div>
				

				<p class="description">Diseño, desarrollo y construcción de componentes de <i>hardware</i> y <i>software</i> especializados para el sistema de monitoreo y control vehicular para el transporte interno de la UNAM usando tecnología GPS y GPRS.</p>
				<p class="bio">Técnico Académico Titular "B" en el Departamento de Ingeniería de Sistemas Computacionales y Automatización en el IIMAS.</p>
				<p class="email">hgomez@leibniz.iimas.unam.mx</p>
			</li>
			<li class="no-border">
				<p class="name">Alejandro Eduardo Cruz Paz</p>
				<div class="photo centered alex"></div>
				
				<p class="description">Conceptualización, diseño y desarrollo tanto del servidor de datos dinámicos, así como también de la primer versión de las aplicaciones móviles y web del proyecto Pumabús Móvil.</p>
				<p class="bio">Estudiante de la Licenciatura en Ciencias de la Computación en la Facultad de Ciencias de la UNAM.</p>
				<p class="email">aecp@ciencias.unam.mx</p>
			</li>

		</ul>
	</div>
	<div id="contribute" class="blocky">
		<h1><%= t('contribute.title') %></h1>
		<div class="content centered">
			<h3><%= t('contribute.main') %></h3>
			<p class="main-follow"><%= t('contribute.main_follow') %></p>
			
			<ul class="contributions centered">
				<li>
					<div class="cartography icon"></div>
					<p class="aspect"><%= t('contribute.cartography.title') %></p>
					<p class="description"><%= t('contribute.cartography.description').html_safe %></p>
					<p class="hot"><%= t('contribute.cartography.hot') %></p>
				</li>
				<li>
					<div class="hardware icon"></div>
					<p class="aspect"><%= t('contribute.hardware.title') %></p>
					<p class="description"><%= t('contribute.hardware.description') %></p>
					<p class="hot"><%= t('contribute.hardware.hot') %></p>
				</li>
				<li>
					<div class="design icon"></div>
					<p class="aspect"><%= t('contribute.design.title') %></p>
					<p class="description"><%= t('contribute.design.description') %></p>
					<p class="hot"><%= t('contribute.design.hot') %></p>
					
					<p class="contributors">+</p>
					<div class="credits hidden">
						<p class="title">Han contribuido:</p>
						<div class="contribution">
								<p class="name">Hugo Dorantes</p>
								<p class="contribution">Diseño del icono del proyecto <a href="http://www.behance.net/hugodr" target="blank" class="contact">Contacto</a></p>
						</div>
					</div>
				</li>
				<li>
					<div class="terminal icon"></div>
					<p class="aspect"><%= t('contribute.software.title') %></p>
					<p class="description"><%= t('contribute.software.description') %></p>
					<p class="hot"><%= t('contribute.software.hot') %></p>
				</li>
			</ul>
			<p class="contact"><%= t('contribute.contact') %></p>
			
		</div>
	</div>
	<div id="api">
		<div class="content centered">
			<p><%= t('contribute.open_api').html_safe %></p>
		</div>
	</div>
	<div id="social" class="blocky">
		<div class="centered content">
			<h2><%= t('social.twitter')%> </h2>
			<%= link_to '', 'https://twitter.com/pumabusapp' , :target => "blank" , :class => "twitter" %>
		</div>
	</div>
	<div id="footer" class="blocky">
		<p>Ciudad Universitaria , <a href="http://www.unam.mx" target="_blank">UNAM</a> 2012</p>
	</div>
</div>